version: "2"
linters:
  default: all
  disable:
    - exhaustruct
    - nlreturn
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - lll
          - varnamelen
        path: _test\.go
      - linters:
          - gochecknoglobals
          - lll
        path: main\.go
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/bengarrett/namzd/cp
            - github.com/bengarrett/namzd/ls
            - github.com/alecthomas/kong
            - github.com/charlievieth/fastwalk
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
