version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - nlreturn
    - paralleltest
    - wsl
    - lll
    - dupl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - varnamelen
        path: _test\.go
      - linters:
          - gochecknoglobals
        path: main\.go
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$